import { MigrationInterface, QueryRunner } from "typeorm";

export class KhoiTaoSchema1791452138741 implements MigrationInterface {
    name = 'KhoiTaoSchema1791452138741'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Khoa chinh cua moi bang deu mac dinh uuid_generate_v4(), ma ham do
        // nam trong extension uuid-ossp chu khong co san trong Postgres. May
        // lap trinh thuong da co san tu truoc nen khong de y; con mot database
        // vua tao tren dich vu cho thue thi trong khong, thieu dong nay la chet
        // ngay o lenh CREATE TABLE dau tien.
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TYPE "public"."service_histories_type_enum" AS ENUM('MAINTENANCE', 'REPAIR', 'INSPECTION', 'PACKAGE')`);
        await queryRunner.query(`CREATE TABLE "service_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "vehicle_id" uuid NOT NULL, "work_order_id" uuid, "store_id" uuid NOT NULL, "serviced_at" TIMESTAMP WITH TIME ZONE NOT NULL, "type" "public"."service_histories_type_enum" NOT NULL, "summary" character varying(255) NOT NULL, "detail" text, "odometer" integer, "total_amount" integer NOT NULL DEFAULT '0', "item_names" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_a09916fb5da3c254a32cd43f2b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6545507fa393d9acd4b73dd997" ON "service_histories" ("vehicle_id", "serviced_at") `);
        await queryRunner.query(`CREATE TYPE "public"."vehicles_fuel_type_enum" AS ENUM('GASOLINE', 'ELECTRIC', 'HYBRID')`);
        await queryRunner.query(`CREATE TABLE "vehicles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "customer_id" uuid NOT NULL, "plate_number" character varying(32) NOT NULL, "maker" character varying(64) NOT NULL, "model" character varying(64) NOT NULL, "model_year" integer, "engine_cc" integer, "color" character varying(32), "vin_number" character varying(64), "current_odometer" integer, "photo_urls" jsonb NOT NULL DEFAULT '[]', "nickname" character varying(64), "fuel_type" "public"."vehicles_fuel_type_enum" NOT NULL DEFAULT 'GASOLINE', "note" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_18d8646b59304dce4af3a9e35b6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_616181596406b639fd2abb0dfc" ON "vehicles" ("plate_number") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TYPE "public"."customers_language_enum" AS ENUM('en', 'vi', 'ja')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "phone" character varying(20) NOT NULL, "name" character varying(128) NOT NULL, "name_kana" character varying(128), "email" character varying(128), "address" text, "is_guest" boolean NOT NULL DEFAULT true, "is_active" boolean NOT NULL DEFAULT true, "language" "public"."customers_language_enum" NOT NULL DEFAULT 'ja', "notify_sms" boolean NOT NULL DEFAULT true, "notify_email" boolean NOT NULL DEFAULT false, "internal_note" text, "merged_into_id" uuid, "last_login_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_88acd889fbe17d0e16cc4bc917" ON "customers" ("phone") `);
        await queryRunner.query(`CREATE TABLE "maintenance_schedules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "vehicle_id" uuid NOT NULL, "service_id" uuid, "due_date" date NOT NULL, "due_odometer" integer, "ai_confidence" integer, "is_notified" boolean NOT NULL DEFAULT false, "notified_at" TIMESTAMP WITH TIME ZONE, "is_done" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_2ce3383b6ff08ab48a28f515e4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_344b277ea122460df7e369b046" ON "maintenance_schedules" ("due_date", "is_notified") `);
        await queryRunner.query(`CREATE TABLE "store_business_hours" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "store_id" uuid NOT NULL, "weekday" smallint NOT NULL, "open_time" TIME, "close_time" TIME, "is_closed" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_cedaf5968c6e4eadc1c1f3b420e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b773a6be83cf95407fa17a8b8" ON "store_business_hours" ("store_id", "weekday") `);
        await queryRunner.query(`CREATE TABLE "store_holidays" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "store_id" uuid NOT NULL, "date" date NOT NULL, "reason" character varying(255), CONSTRAINT "PK_2bb68b28111a6e12940ae19e746" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9a5c18a2b69393b721cd2380b5" ON "store_holidays" ("store_id", "date") `);
        await queryRunner.query(`CREATE TABLE "time_slots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "store_id" uuid NOT NULL, "weekday" smallint NOT NULL, "start_time" TIME NOT NULL, "end_time" TIME NOT NULL, "capacity" integer NOT NULL DEFAULT '3', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f87c73d8648c3f3f297adba3cb8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b770fa81254bd822a916ca4d83" ON "time_slots" ("store_id", "weekday", "start_time") `);
        await queryRunner.query(`CREATE TABLE "stores" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(32) NOT NULL, "name" jsonb NOT NULL, "description" jsonb, "address" jsonb NOT NULL, "phone" character varying(32) NOT NULL, "fax" character varying(32), "email" character varying(128), "latitude" numeric(10,7), "longitude" numeric(10,7), "photo_urls" jsonb NOT NULL DEFAULT '[]', "default_capacity" integer NOT NULL DEFAULT '3', "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_72bdebc754d6a689b3c169cab8a" UNIQUE ("code"), CONSTRAINT "PK_7aa6e7d71fa7acdd7ca43d7c9cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "price_rules" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "service_id" uuid NOT NULL, "store_id" uuid, "engine_cc_from" integer, "engine_cc_to" integer, "difficulty_level" smallint NOT NULL DEFAULT '1', "price" integer NOT NULL, "labor_minutes" integer, "valid_from" date, "valid_to" date, "is_active" boolean NOT NULL DEFAULT true, "note" text, CONSTRAINT "PK_332f84d0bdaa08303a9292653f9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."services_type_enum" AS ENUM('MAINTENANCE', 'REPAIR', 'INSPECTION', 'PACKAGE')`);
        await queryRunner.query(`CREATE TABLE "services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "slug" character varying(64) NOT NULL, "code" character varying(32) NOT NULL, "type" "public"."services_type_enum" NOT NULL, "name" jsonb NOT NULL, "short_description" jsonb, "description" jsonb, "checklist_items" jsonb NOT NULL DEFAULT '[]', "duration_minutes" integer NOT NULL DEFAULT '60', "base_price" integer NOT NULL DEFAULT '0', "quote_only" boolean NOT NULL DEFAULT false, "icon_key" character varying(32), "image_url" character varying(512), "is_active" boolean NOT NULL DEFAULT true, "is_featured" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', "maintenance_interval_months" integer, "maintenance_interval_km" integer, CONSTRAINT "UQ_f019a17cb439406ab185382df9b" UNIQUE ("code"), CONSTRAINT "PK_ba2d347a3168a296416c6c5ccb2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_02cf0d0f46e11d22d952f62367" ON "services" ("slug") `);
        await queryRunner.query(`CREATE TABLE "inventories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "store_id" uuid NOT NULL, "part_id" uuid NOT NULL, "quantity" integer NOT NULL DEFAULT '0', "min_quantity" integer NOT NULL DEFAULT '0', "location_note" character varying(128), CONSTRAINT "PK_7b1946392ffdcb50cfc6ac78c0e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2919304283bf58b86398c76c3f" ON "inventories" ("store_id", "part_id") `);
        await queryRunner.query(`CREATE TABLE "parts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "code" character varying(64) NOT NULL, "name" jsonb NOT NULL, "maker" character varying(128), "maker_part_no" character varying(64), "category" character varying(64), "specification" character varying(128), "unit" character varying(16) NOT NULL DEFAULT 'pcs', "cost_price" integer NOT NULL DEFAULT '0', "sell_price" integer NOT NULL DEFAULT '0', "compatible_vehicles" jsonb NOT NULL DEFAULT '[]', "image_urls" jsonb NOT NULL DEFAULT '[]', "created_source" character varying(16) NOT NULL DEFAULT 'MANUAL', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_daa5595bb8933f49ac00c9ebc79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_53a67950870596e39ae1e75551" ON "parts" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_transactions_type_enum" AS ENUM('IN', 'OUT', 'ADJUST', 'RETURN')`);
        await queryRunner.query(`CREATE TABLE "inventory_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "store_id" uuid NOT NULL, "part_id" uuid NOT NULL, "type" "public"."inventory_transactions_type_enum" NOT NULL, "quantity_change" integer NOT NULL, "quantity_after" integer NOT NULL, "unit_cost" integer, "work_order_id" uuid, "performed_by_id" uuid, "reason" text, CONSTRAINT "PK_9b7144851f08f9eededde7edd42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b93bb948588a9081390680086d" ON "inventory_transactions" ("store_id", "part_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "booking_services" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "booking_id" uuid NOT NULL, "service_id" uuid, "service_name" character varying(255) NOT NULL, "estimated_price" integer NOT NULL DEFAULT '0', "estimated_minutes" integer NOT NULL DEFAULT '60', CONSTRAINT "PK_8997bf4d0728c8740c87694d59a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_histories_from_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'RECEIVED', 'DONE', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`CREATE TYPE "public"."booking_status_histories_to_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'RECEIVED', 'DONE', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`CREATE TABLE "booking_status_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "booking_id" uuid NOT NULL, "from_status" "public"."booking_status_histories_from_status_enum", "to_status" "public"."booking_status_histories_to_status_enum" NOT NULL, "action" character varying(32) NOT NULL DEFAULT 'STATUS_CHANGE', "actor_type" character varying(16) NOT NULL, "actor_id" uuid, "note" text, "previous_scheduled_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_cf024125193d381e989bfefa3de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fff0394e20750eacdd12a36692" ON "booking_status_histories" ("booking_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('PENDING', 'CONFIRMED', 'RECEIVED', 'DONE', 'CANCELLED', 'NO_SHOW')`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_service_type_enum" AS ENUM('MAINTENANCE', 'REPAIR', 'INSPECTION', 'BOTH')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(24) NOT NULL, "customer_id" uuid NOT NULL, "vehicle_id" uuid, "store_id" uuid NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'PENDING', "service_type" "public"."bookings_service_type_enum" NOT NULL, "scheduled_at" TIMESTAMP WITH TIME ZONE NOT NULL, "slot_start_time" TIME NOT NULL, "slot_end_time" TIME NOT NULL, "contact_name" character varying(128) NOT NULL, "contact_phone" character varying(20) NOT NULL, "contact_email" character varying(128), "symptom_description" text, "symptom_photo_urls" jsonb NOT NULL DEFAULT '[]', "symptom_video_url" text, "ai_diagnosis_id" uuid, "created_by_admin" boolean NOT NULL DEFAULT false, "created_by_admin_id" uuid, "rebooked_from_id" uuid, "qr_token" character varying(64), "qr_issued_at" TIMESTAMP WITH TIME ZONE, "qr_used_at" TIMESTAMP WITH TIME ZONE, "confirmed_at" TIMESTAMP WITH TIME ZONE, "received_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancel_reason" text, "cancelled_by" character varying(16), "reminder_sent_at" TIMESTAMP WITH TIME ZONE, "admin_note" text, CONSTRAINT "UQ_5097203bc245a4ac947d3ffe260" UNIQUE ("qr_token"), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9add00bfd42ae2bbe830bab9aa" ON "bookings" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_242433d60f33880333a8e01c31" ON "bookings" ("status", "scheduled_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ea2527eab8e6b5eea3b74212e0" ON "bookings" ("store_id", "scheduled_at") `);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_role_enum" AS ENUM('ADMIN', 'STAFF')`);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_language_enum" AS ENUM('en', 'vi', 'ja')`);
        await queryRunner.query(`CREATE TABLE "admin_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "username" character varying(64) NOT NULL, "email" character varying(128), "password_hash" character varying(255) NOT NULL, "full_name" character varying(128) NOT NULL, "phone" character varying(32), "role" "public"."admin_users_role_enum" NOT NULL DEFAULT 'STAFF', "store_id" uuid, "language" "public"."admin_users_language_enum" NOT NULL DEFAULT 'ja', "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "failed_login_count" smallint NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, "must_change_password" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_06744d221bb6145dc61e5dc441d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2873882c38e8c07d98cb64f962" ON "admin_users" ("username") `);
        await queryRunner.query(`CREATE TYPE "public"."work_order_items_state_enum" AS ENUM('PENDING', 'IN_PROGRESS', 'DONE')`);
        await queryRunner.query(`CREATE TABLE "work_order_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "work_order_id" uuid NOT NULL, "service_id" uuid, "name" character varying(255) NOT NULL, "description" text, "unit_price" integer NOT NULL DEFAULT '0', "quantity" integer NOT NULL DEFAULT '1', "labor_minutes" integer, "suggested_by_ai" boolean NOT NULL DEFAULT false, "state" "public"."work_order_items_state_enum" NOT NULL DEFAULT 'PENDING', "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_857f8e431138c3ef8c2febe6ebf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_parts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "work_order_id" uuid NOT NULL, "part_id" uuid, "part_name" character varying(255) NOT NULL, "part_code" character varying(64), "unit_price" integer NOT NULL DEFAULT '0', "quantity" integer NOT NULL DEFAULT '1', "suggested_by_ai" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_f940468276c041deed13cd240cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_order_photos" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "work_order_id" uuid NOT NULL, "stage" character varying(16) NOT NULL, "url" text NOT NULL, "caption" character varying(255), "visible_to_customer" boolean NOT NULL DEFAULT false, "uploaded_by_id" uuid, CONSTRAINT "PK_ebd20ac413b724104207877fc9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."work_order_status_histories_from_status_enum" AS ENUM('RECEIVED', 'DIAGNOSING', 'QUOTED', 'IN_PROGRESS', 'COMPLETED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."work_order_status_histories_to_status_enum" AS ENUM('RECEIVED', 'DIAGNOSING', 'QUOTED', 'IN_PROGRESS', 'COMPLETED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "work_order_status_histories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "work_order_id" uuid NOT NULL, "from_status" "public"."work_order_status_histories_from_status_enum", "to_status" "public"."work_order_status_histories_to_status_enum" NOT NULL, "actor_id" uuid, "note" text, "visible_to_customer" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_1a14de3ac580de368422148e04e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54f757875eebe8e5428bb3fa30" ON "work_order_status_histories" ("work_order_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."work_orders_status_enum" AS ENUM('RECEIVED', 'DIAGNOSING', 'QUOTED', 'IN_PROGRESS', 'COMPLETED', 'DELIVERED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."work_orders_payment_status_enum" AS ENUM('UNPAID', 'PARTIAL', 'PAID')`);
        await queryRunner.query(`CREATE TYPE "public"."work_orders_difficulty_enum" AS ENUM('EASY', 'MEDIUM', 'HARD')`);
        await queryRunner.query(`CREATE TABLE "work_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(24) NOT NULL, "booking_id" uuid, "customer_id" uuid NOT NULL, "vehicle_id" uuid NOT NULL, "store_id" uuid NOT NULL, "status" "public"."work_orders_status_enum" NOT NULL DEFAULT 'RECEIVED', "payment_status" "public"."work_orders_payment_status_enum" NOT NULL DEFAULT 'UNPAID', "intake_odometer" integer NOT NULL, "intake_fuel_level" smallint, "intake_accessories" character varying(255), "intake_note" text, "customer_symptom" text, "diagnosis_note" text, "diagnosis_cause" text, "diagnosed_by_id" uuid, "diagnosed_at" TIMESTAMP WITH TIME ZONE, "assigned_technician_id" uuid, "difficulty" "public"."work_orders_difficulty_enum", "received_by_id" uuid, "progress_percent" smallint NOT NULL DEFAULT '0', "progress_note" text, "estimated_completion_at" TIMESTAMP WITH TIME ZONE, "labor_subtotal" integer NOT NULL DEFAULT '0', "parts_subtotal" integer NOT NULL DEFAULT '0', "discount_amount" integer NOT NULL DEFAULT '0', "tax_rate" smallint NOT NULL DEFAULT '10', "tax_amount" integer NOT NULL DEFAULT '0', "total_amount" integer NOT NULL DEFAULT '0', "paid_amount" integer NOT NULL DEFAULT '0', "diagnosing_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "completed_at" TIMESTAMP WITH TIME ZONE, "delivered_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "cancel_reason" text, "stock_deducted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_29f6c1884082ee6f535aed93660" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ca7b6602b744e246946406bd49" ON "work_orders" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_6596ad31099ce12bbcbe063fb1" ON "work_orders" ("status", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_9a078b754d102c0add3032642b" ON "work_orders" ("store_id", "status") `);
        await queryRunner.query(`CREATE TABLE "quotation_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "quotation_id" uuid NOT NULL, "kind" character varying(16) NOT NULL DEFAULT 'LABOR', "service_id" uuid, "part_id" uuid, "name" character varying(255) NOT NULL, "description" text, "unit_price" integer NOT NULL DEFAULT '0', "quantity" integer NOT NULL DEFAULT '1', "line_total" integer NOT NULL DEFAULT '0', "is_optional" boolean NOT NULL DEFAULT false, "is_accepted" boolean NOT NULL DEFAULT true, "suggested_by_ai" boolean NOT NULL DEFAULT false, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_a5ff0786836b65d12bafd0ac91e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."quotations_status_enum" AS ENUM('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'SUPERSEDED')`);
        await queryRunner.query(`CREATE TYPE "public"."quotations_responded_via_enum" AS ENUM('LINK', 'COUNTER', 'PHONE')`);
        await queryRunner.query(`CREATE TABLE "quotations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "code" character varying(24) NOT NULL, "work_order_id" uuid NOT NULL, "customer_id" uuid NOT NULL, "version" integer NOT NULL DEFAULT '1', "status" "public"."quotations_status_enum" NOT NULL DEFAULT 'DRAFT', "public_token" character varying(64) NOT NULL, "subtotal" integer NOT NULL DEFAULT '0', "discount_amount" integer NOT NULL DEFAULT '0', "tax_rate" smallint NOT NULL DEFAULT '10', "tax_amount" integer NOT NULL DEFAULT '0', "total_amount" integer NOT NULL DEFAULT '0', "valid_until" date, "deposit_amount" integer, "deposit_due_at" TIMESTAMP WITH TIME ZONE, "note" text, "ai_suggestion" jsonb, "created_by_id" uuid, "sent_at" TIMESTAMP WITH TIME ZONE, "responded_at" TIMESTAMP WITH TIME ZONE, "reject_reason" text, "revision_requested" boolean NOT NULL DEFAULT false, "responded_via" "public"."quotations_responded_via_enum", "recorded_by_id" uuid, "customer_comment" text, CONSTRAINT "PK_6c00eb8ba181f28c21ffba7ecb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b0e9bdd9d2ca51b024e91ca3bb" ON "quotations" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ed8e71b60f6eecd40e078a4de3" ON "quotations" ("public_token") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91e3d2beb48dea9b6da916540c" ON "quotations" ("work_order_id", "version") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('CASH', 'BANK_TRANSFER', 'CARD_AT_STORE', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "work_order_id" uuid NOT NULL, "amount" integer NOT NULL, "method" "public"."payments_method_enum" NOT NULL DEFAULT 'CASH', "paid_at" TIMESTAMP WITH TIME ZONE NOT NULL, "receipt_no" character varying(64), "received_by_id" uuid, "note" text, "is_voided" boolean NOT NULL DEFAULT false, "void_reason" text, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c46562705e471504e934c9ee76" ON "payments" ("work_order_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_diagnoses_language_enum" AS ENUM('en', 'vi', 'ja')`);
        await queryRunner.query(`CREATE TABLE "ai_diagnoses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customer_id" uuid, "session_key" character varying(64) NOT NULL, "language" "public"."ai_diagnoses_language_enum" NOT NULL DEFAULT 'ja', "vehicle_maker" character varying(64), "vehicle_model" character varying(64), "vehicle_year" integer, "service_intent" character varying(64), "messages" jsonb NOT NULL DEFAULT '[]', "findings" jsonb NOT NULL DEFAULT '[]', "summary_text" text, "status" character varying(16) NOT NULL DEFAULT 'PENDING', "model_name" character varying(64), "latency_ms" integer, "booking_id" uuid, "media_expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f3e2ee5af390139b5bf25eb2fed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_105aaa2df637ccab2e620b4346" ON "ai_diagnoses" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "knowledge_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "title" character varying(255) NOT NULL, "category" character varying(64), "applicable_makers" jsonb NOT NULL DEFAULT '[]', "applicable_models" jsonb NOT NULL DEFAULT '[]', "file_url" character varying(512), "file_type" character varying(16), "content" text, "page_count" integer, "index_status" character varying(16) NOT NULL DEFAULT 'PENDING', "indexed_at" TIMESTAMP WITH TIME ZONE, "uploaded_by_id" uuid, CONSTRAINT "PK_402a3c43fb263aa5289670e4e21" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_201aad01dfe022f0094e22b213" ON "knowledge_documents" ("category") `);
        await queryRunner.query(`CREATE TABLE "otp_codes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "phone" character varying(20) NOT NULL, "purpose" character varying(24) NOT NULL, "code_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "attempt_count" smallint NOT NULL DEFAULT '0', "consumed_at" TIMESTAMP WITH TIME ZONE, "ip_address" character varying(64), CONSTRAINT "PK_9d0487965ac1837d57fec4d6a26" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_64befb7e2066a0c05338c5f81c" ON "otp_codes" ("phone", "purpose", "consumed_at") `);
        await queryRunner.query(`CREATE TYPE "public"."refresh_tokens_subject_role_enum" AS ENUM('R-GUEST', 'R-USER', 'R-ADMIN')`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "subject_id" uuid NOT NULL, "subject_role" "public"."refresh_tokens_subject_role_enum" NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "revoked_at" TIMESTAMP WITH TIME ZONE, "user_agent" character varying(255), "ip_address" character varying(64), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6c642019c7231f8cfa8ce5ca1" ON "refresh_tokens" ("subject_id", "revoked_at") `);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "admin_user_id" uuid NOT NULL, "token_hash" character varying(255) NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "consumed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_592c5ad2fabb74e1e19e75358c" ON "password_reset_tokens" ("admin_user_id", "consumed_at") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_event_enum" AS ENUM('BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_REMINDER', 'BOOKING_CANCELLED', 'BOOKING_RESCHEDULED', 'QUOTATION_SENT', 'QUOTATION_ACCEPTED', 'WORK_ORDER_COMPLETED', 'VEHICLE_DELIVERED', 'MAINTENANCE_DUE', 'OTP', 'ADMIN_PASSWORD_RESET')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_channel_enum" AS ENUM('SMS', 'EMAIL')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_templates_language_enum" AS ENUM('en', 'vi', 'ja')`);
        await queryRunner.query(`CREATE TABLE "notification_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event" "public"."notification_templates_event_enum" NOT NULL, "channel" "public"."notification_templates_channel_enum" NOT NULL, "language" "public"."notification_templates_language_enum" NOT NULL, "subject" character varying(255), "body" text NOT NULL, "available_variables" jsonb NOT NULL DEFAULT '[]', "is_active" boolean NOT NULL DEFAULT true, "updated_by_id" uuid, CONSTRAINT "PK_76f0fc48b8d057d2ae7f3a2848a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_cbff71e032c4c561232d37bdfa" ON "notification_templates" ("event", "channel", "language") `);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_event_enum" AS ENUM('BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_REMINDER', 'BOOKING_CANCELLED', 'BOOKING_RESCHEDULED', 'QUOTATION_SENT', 'QUOTATION_ACCEPTED', 'WORK_ORDER_COMPLETED', 'VEHICLE_DELIVERED', 'MAINTENANCE_DUE', 'OTP', 'ADMIN_PASSWORD_RESET')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_channel_enum" AS ENUM('SMS', 'EMAIL')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_language_enum" AS ENUM('en', 'vi', 'ja')`);
        await queryRunner.query(`CREATE TYPE "public"."notification_logs_status_enum" AS ENUM('QUEUED', 'SENT', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "notification_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "customer_id" uuid, "event" "public"."notification_logs_event_enum" NOT NULL, "channel" "public"."notification_logs_channel_enum" NOT NULL, "language" "public"."notification_logs_language_enum" NOT NULL, "recipient" character varying(128) NOT NULL, "subject" character varying(255), "body" text NOT NULL, "status" "public"."notification_logs_status_enum" NOT NULL DEFAULT 'QUEUED', "sent_at" TIMESTAMP WITH TIME ZONE, "read_at" TIMESTAMP WITH TIME ZONE, "booking_code" character varying(24), "error_message" text, "retry_count" smallint NOT NULL DEFAULT '0', "provider_message_id" character varying(128), "related_type" character varying(32), "related_id" uuid, CONSTRAINT "PK_19c524e644cdeaebfcffc284871" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_38249684040d7da21c5f96a79d" ON "notification_logs" ("customer_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_845e1c10ac9e3a0e7147bf3072" ON "notification_logs" ("event", "status", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."admin_notifications_event_enum" AS ENUM('BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_REMINDER', 'BOOKING_CANCELLED', 'BOOKING_RESCHEDULED', 'QUOTATION_SENT', 'QUOTATION_ACCEPTED', 'WORK_ORDER_COMPLETED', 'VEHICLE_DELIVERED', 'MAINTENANCE_DUE', 'OTP', 'ADMIN_PASSWORD_RESET')`);
        await queryRunner.query(`CREATE TABLE "admin_notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "event" "public"."admin_notifications_event_enum" NOT NULL, "title" character varying(200) NOT NULL, "body" text NOT NULL, "link" character varying(255), "store_id" uuid, "read_by_ids" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_1fecd1cab747b7ab6e850091901" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c37317d42fad919539d82929d9" ON "admin_notifications" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actor_id" uuid, "actor_name" character varying(128), "actor_type" character varying(16) NOT NULL, "action" character varying(64) NOT NULL, "entity" character varying(64) NOT NULL, "entity_id" uuid, "changes" jsonb, "ip_address" character varying(64), "user_agent" character varying(255), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a85d553dbb4006bd350ab6f88" ON "audit_logs" ("actor_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_6348fc72642e4c950fb40820b2" ON "audit_logs" ("entity", "entity_id", "created_at") `);
        await queryRunner.query(`CREATE TABLE "system_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "key" character varying(64) NOT NULL, "value" jsonb NOT NULL, "value_type" character varying(16) NOT NULL DEFAULT 'STRING', "group" character varying(64), "description" character varying(255), "is_editable" boolean NOT NULL DEFAULT true, "updated_by_id" uuid, CONSTRAINT "PK_82521f08790d248b2a80cc85d40" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b1b5bc664526d375c94ce9ad43" ON "system_settings" ("key") `);
        await queryRunner.query(`CREATE TABLE "faqs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "question" jsonb NOT NULL, "answer" jsonb NOT NULL, "category" character varying(64), "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_2ddf4f2c910f8e8fa2663a67bf0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."contact_messages_language_enum" AS ENUM('en', 'vi', 'ja')`);
        await queryRunner.query(`CREATE TABLE "contact_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "name" character varying(128) NOT NULL, "phone" character varying(20), "email" character varying(128), "store_id" uuid, "subject" character varying(255), "message" text NOT NULL, "language" "public"."contact_messages_language_enum" NOT NULL DEFAULT 'ja', "is_handled" boolean NOT NULL DEFAULT false, "handled_by_id" uuid, "handled_at" TIMESTAMP WITH TIME ZONE, "handler_note" text, CONSTRAINT "PK_b74f96eb2edd977ccfba6533293" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3edcf24830afaf1a2fbf301d77" ON "contact_messages" ("is_handled", "created_at") `);
        await queryRunner.query(`ALTER TABLE "service_histories" ADD CONSTRAINT "FK_0fc92b8e0e81a7ce4b81b71c931" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicles" ADD CONSTRAINT "FK_c1cda98f67cb9c79a1f1153e627" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_schedules" ADD CONSTRAINT "FK_0dd4012f966f9e4ead7f0e8d08d" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_business_hours" ADD CONSTRAINT "FK_8c40c77b21a7b63f81116a732e6" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_holidays" ADD CONSTRAINT "FK_64cae3869e80ac6b4efd133deb1" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "time_slots" ADD CONSTRAINT "FK_3cc07d1542dbd2ef1707eede5c5" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_rules" ADD CONSTRAINT "FK_884e71536a3bbea21829778b47d" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_676a2ef2e301391abf39e8700c7" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventories" ADD CONSTRAINT "FK_0d93988a0936f99d563b45528e5" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_57b4dc7c37c3780ff4e93a7f3db" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" ADD CONSTRAINT "FK_5f7103a00fc561a7678f2c3bd54" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_813fb23d7e327b6d9cff929cce6" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_services" ADD CONSTRAINT "FK_6e853453a3c24df1beed35c13eb" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_status_histories" ADD CONSTRAINT "FK_746998f688d207c9cf08b9feedd" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_314ee41921742fb13c9309e4054" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_cebf89b278facba16b3273ca01f" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_users" ADD CONSTRAINT "FK_1c760e26a1527825c2bbd50caa4" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_items" ADD CONSTRAINT "FK_ba6cdb46e971e7cadc36b4f8050" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_items" ADD CONSTRAINT "FK_aebddd02f52379249a109692663" FOREIGN KEY ("service_id") REFERENCES "services"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_parts" ADD CONSTRAINT "FK_f0cd99de92dd30d18f97bf3e51b" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_parts" ADD CONSTRAINT "FK_755e76456ba17545dc3f9b44f80" FOREIGN KEY ("part_id") REFERENCES "parts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_photos" ADD CONSTRAINT "FK_3b232957a1b6082775dbdd30f44" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order_status_histories" ADD CONSTRAINT "FK_35b0b6b6c204c7b2fd6f4baa5e0" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_bde32cd152e1b31eafb768c12ec" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_a9cd45a23c6212aaa1737d69163" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_18fb19db181c9e178cc8e5b6c8f" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_aa0e6c950eb265aa96b096abebb" FOREIGN KEY ("store_id") REFERENCES "stores"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_885d6f7169ea9678e4419d37779" FOREIGN KEY ("diagnosed_by_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_orders" ADD CONSTRAINT "FK_72667a721b2f13a520988227a0f" FOREIGN KEY ("assigned_technician_id") REFERENCES "admin_users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotation_items" ADD CONSTRAINT "FK_c9e2dea84928feba1d24874c160" FOREIGN KEY ("quotation_id") REFERENCES "quotations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotations" ADD CONSTRAINT "FK_960070a8a6934cf9a57d605ea65" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotations" ADD CONSTRAINT "FK_6c655818e6753ed41eb755b8bcb" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_1e6c3ef82e56da42e89cbd5d77a" FOREIGN KEY ("work_order_id") REFERENCES "work_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_1e6c3ef82e56da42e89cbd5d77a"`);
        await queryRunner.query(`ALTER TABLE "quotations" DROP CONSTRAINT "FK_6c655818e6753ed41eb755b8bcb"`);
        await queryRunner.query(`ALTER TABLE "quotations" DROP CONSTRAINT "FK_960070a8a6934cf9a57d605ea65"`);
        await queryRunner.query(`ALTER TABLE "quotation_items" DROP CONSTRAINT "FK_c9e2dea84928feba1d24874c160"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_72667a721b2f13a520988227a0f"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_885d6f7169ea9678e4419d37779"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_aa0e6c950eb265aa96b096abebb"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_18fb19db181c9e178cc8e5b6c8f"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_a9cd45a23c6212aaa1737d69163"`);
        await queryRunner.query(`ALTER TABLE "work_orders" DROP CONSTRAINT "FK_bde32cd152e1b31eafb768c12ec"`);
        await queryRunner.query(`ALTER TABLE "work_order_status_histories" DROP CONSTRAINT "FK_35b0b6b6c204c7b2fd6f4baa5e0"`);
        await queryRunner.query(`ALTER TABLE "work_order_photos" DROP CONSTRAINT "FK_3b232957a1b6082775dbdd30f44"`);
        await queryRunner.query(`ALTER TABLE "work_order_parts" DROP CONSTRAINT "FK_755e76456ba17545dc3f9b44f80"`);
        await queryRunner.query(`ALTER TABLE "work_order_parts" DROP CONSTRAINT "FK_f0cd99de92dd30d18f97bf3e51b"`);
        await queryRunner.query(`ALTER TABLE "work_order_items" DROP CONSTRAINT "FK_aebddd02f52379249a109692663"`);
        await queryRunner.query(`ALTER TABLE "work_order_items" DROP CONSTRAINT "FK_ba6cdb46e971e7cadc36b4f8050"`);
        await queryRunner.query(`ALTER TABLE "admin_users" DROP CONSTRAINT "FK_1c760e26a1527825c2bbd50caa4"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_cebf89b278facba16b3273ca01f"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_314ee41921742fb13c9309e4054"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_8e21b7ae33e7b0673270de4146f"`);
        await queryRunner.query(`ALTER TABLE "booking_status_histories" DROP CONSTRAINT "FK_746998f688d207c9cf08b9feedd"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_6e853453a3c24df1beed35c13eb"`);
        await queryRunner.query(`ALTER TABLE "booking_services" DROP CONSTRAINT "FK_813fb23d7e327b6d9cff929cce6"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_5f7103a00fc561a7678f2c3bd54"`);
        await queryRunner.query(`ALTER TABLE "inventory_transactions" DROP CONSTRAINT "FK_57b4dc7c37c3780ff4e93a7f3db"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_0d93988a0936f99d563b45528e5"`);
        await queryRunner.query(`ALTER TABLE "inventories" DROP CONSTRAINT "FK_676a2ef2e301391abf39e8700c7"`);
        await queryRunner.query(`ALTER TABLE "price_rules" DROP CONSTRAINT "FK_884e71536a3bbea21829778b47d"`);
        await queryRunner.query(`ALTER TABLE "time_slots" DROP CONSTRAINT "FK_3cc07d1542dbd2ef1707eede5c5"`);
        await queryRunner.query(`ALTER TABLE "store_holidays" DROP CONSTRAINT "FK_64cae3869e80ac6b4efd133deb1"`);
        await queryRunner.query(`ALTER TABLE "store_business_hours" DROP CONSTRAINT "FK_8c40c77b21a7b63f81116a732e6"`);
        await queryRunner.query(`ALTER TABLE "maintenance_schedules" DROP CONSTRAINT "FK_0dd4012f966f9e4ead7f0e8d08d"`);
        await queryRunner.query(`ALTER TABLE "vehicles" DROP CONSTRAINT "FK_c1cda98f67cb9c79a1f1153e627"`);
        await queryRunner.query(`ALTER TABLE "service_histories" DROP CONSTRAINT "FK_0fc92b8e0e81a7ce4b81b71c931"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3edcf24830afaf1a2fbf301d77"`);
        await queryRunner.query(`DROP TABLE "contact_messages"`);
        await queryRunner.query(`DROP TYPE "public"."contact_messages_language_enum"`);
        await queryRunner.query(`DROP TABLE "faqs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1b5bc664526d375c94ce9ad43"`);
        await queryRunner.query(`DROP TABLE "system_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6348fc72642e4c950fb40820b2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a85d553dbb4006bd350ab6f88"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c37317d42fad919539d82929d9"`);
        await queryRunner.query(`DROP TABLE "admin_notifications"`);
        await queryRunner.query(`DROP TYPE "public"."admin_notifications_event_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_845e1c10ac9e3a0e7147bf3072"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38249684040d7da21c5f96a79d"`);
        await queryRunner.query(`DROP TABLE "notification_logs"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_logs_event_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbff71e032c4c561232d37bdfa"`);
        await queryRunner.query(`DROP TABLE "notification_templates"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notification_templates_event_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_592c5ad2fabb74e1e19e75358c"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6c642019c7231f8cfa8ce5ca1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TYPE "public"."refresh_tokens_subject_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_64befb7e2066a0c05338c5f81c"`);
        await queryRunner.query(`DROP TABLE "otp_codes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_201aad01dfe022f0094e22b213"`);
        await queryRunner.query(`DROP TABLE "knowledge_documents"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_105aaa2df637ccab2e620b4346"`);
        await queryRunner.query(`DROP TABLE "ai_diagnoses"`);
        await queryRunner.query(`DROP TYPE "public"."ai_diagnoses_language_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c46562705e471504e934c9ee76"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91e3d2beb48dea9b6da916540c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed8e71b60f6eecd40e078a4de3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0e9bdd9d2ca51b024e91ca3bb"`);
        await queryRunner.query(`DROP TABLE "quotations"`);
        await queryRunner.query(`DROP TYPE "public"."quotations_responded_via_enum"`);
        await queryRunner.query(`DROP TYPE "public"."quotations_status_enum"`);
        await queryRunner.query(`DROP TABLE "quotation_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a078b754d102c0add3032642b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6596ad31099ce12bbcbe063fb1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca7b6602b744e246946406bd49"`);
        await queryRunner.query(`DROP TABLE "work_orders"`);
        await queryRunner.query(`DROP TYPE "public"."work_orders_difficulty_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_orders_payment_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54f757875eebe8e5428bb3fa30"`);
        await queryRunner.query(`DROP TABLE "work_order_status_histories"`);
        await queryRunner.query(`DROP TYPE "public"."work_order_status_histories_to_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."work_order_status_histories_from_status_enum"`);
        await queryRunner.query(`DROP TABLE "work_order_photos"`);
        await queryRunner.query(`DROP TABLE "work_order_parts"`);
        await queryRunner.query(`DROP TABLE "work_order_items"`);
        await queryRunner.query(`DROP TYPE "public"."work_order_items_state_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2873882c38e8c07d98cb64f962"`);
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_language_enum"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ea2527eab8e6b5eea3b74212e0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_242433d60f33880333a8e01c31"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9add00bfd42ae2bbe830bab9aa"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_service_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fff0394e20750eacdd12a36692"`);
        await queryRunner.query(`DROP TABLE "booking_status_histories"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_histories_to_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."booking_status_histories_from_status_enum"`);
        await queryRunner.query(`DROP TABLE "booking_services"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b93bb948588a9081390680086d"`);
        await queryRunner.query(`DROP TABLE "inventory_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53a67950870596e39ae1e75551"`);
        await queryRunner.query(`DROP TABLE "parts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2919304283bf58b86398c76c3f"`);
        await queryRunner.query(`DROP TABLE "inventories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_02cf0d0f46e11d22d952f62367"`);
        await queryRunner.query(`DROP TABLE "services"`);
        await queryRunner.query(`DROP TYPE "public"."services_type_enum"`);
        await queryRunner.query(`DROP TABLE "price_rules"`);
        await queryRunner.query(`DROP TABLE "stores"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b770fa81254bd822a916ca4d83"`);
        await queryRunner.query(`DROP TABLE "time_slots"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9a5c18a2b69393b721cd2380b5"`);
        await queryRunner.query(`DROP TABLE "store_holidays"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b773a6be83cf95407fa17a8b8"`);
        await queryRunner.query(`DROP TABLE "store_business_hours"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_344b277ea122460df7e369b046"`);
        await queryRunner.query(`DROP TABLE "maintenance_schedules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88acd889fbe17d0e16cc4bc917"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_language_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_616181596406b639fd2abb0dfc"`);
        await queryRunner.query(`DROP TABLE "vehicles"`);
        await queryRunner.query(`DROP TYPE "public"."vehicles_fuel_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6545507fa393d9acd4b73dd997"`);
        await queryRunner.query(`DROP TABLE "service_histories"`);
        await queryRunner.query(`DROP TYPE "public"."service_histories_type_enum"`);
    }

}
