export enum NotificationChannel {
  SMS = 'SMS',
  EMAIL = 'EMAIL',
}

/** Ma su kien thong bao — khop voi mau tai SA-41. */
export enum NotificationEvent {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_CONFIRMED = 'BOOKING_CONFIRMED',
  BOOKING_REMINDER = 'BOOKING_REMINDER',
  BOOKING_CANCELLED = 'BOOKING_CANCELLED',
  BOOKING_RESCHEDULED = 'BOOKING_RESCHEDULED',
  QUOTATION_SENT = 'QUOTATION_SENT',
  WORK_ORDER_COMPLETED = 'WORK_ORDER_COMPLETED',
  VEHICLE_DELIVERED = 'VEHICLE_DELIVERED',
  MAINTENANCE_DUE = 'MAINTENANCE_DUE',
  OTP = 'OTP',
}

export enum NotificationSendStatus {
  QUEUED = 'QUEUED',
  SENT = 'SENT',
  FAILED = 'FAILED',
}
